version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  install-win:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: nvm --help
      - run: node -v

workflows:
  build-mac:
    jobs:
      - install-win
