version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  install-win:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: install node
          command: |
            nvm install vv12.18.2
            nvm use v12.18.2

      - restore_cache:
          keys:
            - flat-win-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: init project
          command: |
            npm install yarn -g
            yarn config set cache-folder C:\Users\circleci\AppData\Local\yarn\.cache\
            yarn install --frozen-lockfile
          working_directory: C:\Users\circleci\project
          environment:
            ELECTRON_CUSTOM_DIR: C:\Users\circleci\AppData\Local\electron\.cache\

      - save_cache:
          key: flat-win-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - project/node_modules
            - project/src/main-app/node_modules
            - project/src/renderer-app/node_modules
            - project/types-pkg/node_modules
            - C:\Users\circleci\AppData\Local\electron\.cache\
            - C:\Users\circleci\AppData\Local\yarn\.cache\

      - run:
          name: test
          command: |
            echo 111

workflows:
  build-win:
    jobs:
      - install-win
