version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  install-win:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: install node / yarn
          command: |
              nvm install vv12.18.2
              nvm use v12.18.2
              npm install -g yarn
              
      - run:
          name: install yarn 
          command: |
              npm install yarn -g
              yarn config set cache-folder C:\Users\circleci\AppData\Local\yarn\.cache\
              ls
              sleep 10000


# jobs:
#   bar:
#     machine: true
#     steps:
#       - checkout
#       - run:
#           command: echo "building"
#       - run:
#           command: echo "testing"

workflows:
  build-mac:
    jobs:
      - install-win
