version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  install-win:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: nvm install 12.18.2
      - run: nvm use 12.18.2
      - run: nvm alias default v12.18.2
      - run: node -v

workflows:
  build-mac:
    jobs:
      - install-win
