version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  install-win:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: install node
          command: |
              nvm install 12.18.2
              nvm use 12.18.2
              node -v
      - run: yarn -v

# jobs:
#   bar:
#     machine: true
#     steps:
#       - checkout
#       - run:
#           command: echo "building"
#       - run:
#           command: echo "testing"

workflows:
  build-mac:
    jobs:
      - install-win
